# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Node registry
email: vladimir.spasic.86@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Library for building scalable node.js applications with ease
baseurl: "/node-registry"
url: "http://vladaspasic.github.io/"
twitter:
  url: https://twitter.com/VladaSpasic
  username: VladaSpasic
github:
  url: https://github.com/vladaspasic/node-registry
  repo: node-registry
  username:  vladaspasic

# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
  - jekyll-bootstrap-sass
  - jekyll-redirect-from
exclude:
  - theme
  - Gemfile
  - Gemfile.lock

# Sass settings
sass:
  style: compressed

bootstrap:
  assets: true
